
tasks:
  - init: yarn
    command: yarn build
ports:
  - port: 3000
    onOpen: open-browser
vscode:
  extensions:
    - eamodio.gitlens
    - dbaeumer.vscode-eslint
    - esbenp.prettier-vscode
    - bradlc.vscode-tailwindcss
    - pkief.material-icon-theme
    - vivaxy.vscode-conventional-commits
